/**
 * Topic Detection Engine (Layer 1 - Stage 1).
 *
 * Instead of relying on the selected mood alone, we score how much the journal
 * text matches each topic using weighted keyword banks. The topic with the
 * highest score wins, and confidence is the share of total score.
 */

export const TOPIC_LABELS: Record<string, string> = {
  academic: "Academic",
  relationships: "Relationships",
  family: "Family",
  health: "Health",
  weather: "Weather",
  financial: "Financial",
  career: "Career",
  social: "Social",
  "self-care": "Self-Care",
  achievements: "Achievements",
  sports: "Sports",
  sleep: "Sleep",
  travel: "Travel",
  hobbies: "Hobbies",
  "mental-wellness": "Mental Wellness",
};

export interface KeywordEntry {
  pattern: string;
  weight: number;
}

/**
 * Weighted keyword banks. Each matched keyword adds its weight to the topic's
 * score, so a dense topic phrase (e.g. "flood" + "rain" + "commute") beats a
 * single weak match on an unrelated topic.
 */
export const TOPIC_KEYWORDS: Record<string, KeywordEntry[]> = {
  weather: [
    { pattern: "typhoon", weight: 5 },
    { pattern: "monsoon", weight: 5 },
    { pattern: "flood", weight: 4 },
    { pattern: "flooding", weight: 4 },
    { pattern: "thunderstorm", weight: 4 },
    { pattern: "heatwave", weight: 4 },
    { pattern: "storm", weight: 4 },
    { pattern: "snow", weight: 3 },
    { pattern: "snowing", weight: 3 },
    { pattern: "raining", weight: 4 },
    { pattern: "rain", weight: 4 },
    { pattern: "rainy", weight: 4 },
    { pattern: "umbrella", weight: 3 },
    { pattern: "lightning", weight: 3 },
    { pattern: "humid", weight: 3 },
    { pattern: "humidity", weight: 3 },
    { pattern: "commute", weight: 2 },
    { pattern: "commuting", weight: 2 },
    { pattern: "traffic", weight: 2 },
    { pattern: "sunny", weight: 2 },
    { pattern: "sunshine", weight: 2 },
    { pattern: "weather", weight: 2 },
    { pattern: "windy", weight: 2 },
    { pattern: "wind", weight: 1 },
    { pattern: "hot", weight: 1 },
    { pattern: "cold", weight: 2 },
    { pattern: "sun", weight: 1 },
    { pattern: "cloudy", weight: 1 },
    { pattern: "wet", weight: 1 },
    { pattern: "drizzle", weight: 2 },
  ],
  academic: [
    { pattern: "exam", weight: 4 },
    { pattern: "exams", weight: 4 },
    { pattern: "midterm", weight: 4 },
    { pattern: "finals", weight: 4 },
    { pattern: "thesis", weight: 4 },
    { pattern: "deadline", weight: 4 },
    { pattern: "assignment", weight: 4 },
    { pattern: "assignments", weight: 4 },
    { pattern: "quiz", weight: 3 },
    { pattern: "quizzes", weight: 3 },
    { pattern: "homework", weight: 3 },
    { pattern: "professor", weight: 3 },
    { pattern: "lecture", weight: 3 },
    { pattern: "lectures", weight: 3 },
    { pattern: "grade", weight: 3 },
    { pattern: "grades", weight: 3 },
    { pattern: "gpa", weight: 3 },
    { pattern: "scholarship", weight: 3 },
    { pattern: "study", weight: 2 },
    { pattern: "studying", weight: 2 },
    { pattern: "class", weight: 2 },
    { pattern: "classes", weight: 2 },
    { pattern: "course", weight: 2 },
    { pattern: "coursework", weight: 3 },
    { pattern: "project", weight: 3 },
    { pattern: "essay", weight: 3 },
    { pattern: "paper", weight: 2 },
    { pattern: "semester", weight: 2 },
    { pattern: "syllabus", weight: 2 },
    { pattern: "tutor", weight: 3 },
    { pattern: "tutoring", weight: 3 },
    { pattern: "presentation", weight: 3 },
    { pattern: "lab", weight: 2 },
    { pattern: "school", weight: 2 },
    { pattern: "test", weight: 3 },
    { pattern: "final", weight: 3 },
    { pattern: "group project", weight: 4 },
  ],
  relationships: [
    { pattern: "boyfriend", weight: 4 },
    { pattern: "girlfriend", weight: 4 },
    { pattern: "partner", weight: 4 },
    { pattern: "husband", weight: 4 },
    { pattern: "wife", weight: 4 },
    { pattern: "breakup", weight: 4 },
    { pattern: "broke up", weight: 4 },
    { pattern: "relationship", weight: 4 },
    { pattern: "relationships", weight: 4 },
    { pattern: "significant other", weight: 5 },
    { pattern: "crush", weight: 3 },
    { pattern: "dating", weight: 3 },
    { pattern: "romantic", weight: 3 },
    { pattern: "romance", weight: 3 },
    { pattern: "marriage", weight: 3 },
    { pattern: "married", weight: 3 },
    { pattern: "engaged", weight: 3 },
    { pattern: "fianc", weight: 4 },
    { pattern: "cheated", weight: 4 },
    { pattern: "cheating", weight: 4 },
    { pattern: "ex-boyfriend", weight: 4 },
    { pattern: "ex-girlfriend", weight: 4 },
    { pattern: "date", weight: 2 },
    { pattern: "couple", weight: 2 },
    { pattern: "in love", weight: 4 },
    { pattern: "valentine", weight: 3 },
  ],
  family: [
    { pattern: "grandmother", weight: 5 },
    { pattern: "grandfather", weight: 5 },
    { pattern: "grandma", weight: 4 },
    { pattern: "grandpa", weight: 4 },
    { pattern: "mom", weight: 4 },
    { pattern: "dad", weight: 4 },
    { pattern: "mother", weight: 4 },
    { pattern: "father", weight: 4 },
    { pattern: "parents", weight: 4 },
    { pattern: "parent", weight: 4 },
    { pattern: "sister", weight: 3 },
    { pattern: "brother", weight: 3 },
    { pattern: "sibling", weight: 3 },
    { pattern: "siblings", weight: 3 },
    { pattern: "family", weight: 3 },
    { pattern: "cousin", weight: 2 },
    { pattern: "uncle", weight: 2 },
    { pattern: "aunt", weight: 2 },
    { pattern: "relatives", weight: 2 },
    { pattern: "nephew", weight: 2 },
    { pattern: "niece", weight: 2 },
    { pattern: "household", weight: 1 },
    { pattern: "my sister", weight: 4 },
    { pattern: "my brother", weight: 4 },
    { pattern: "my mom", weight: 4 },
    { pattern: "my dad", weight: 4 },
  ],
  health: [
    { pattern: "hospital", weight: 4 },
    { pattern: "surgery", weight: 4 },
    { pattern: "fever", weight: 4 },
    { pattern: "headache", weight: 4 },
    { pattern: "injury", weight: 4 },
    { pattern: "injured", weight: 4 },
    { pattern: "sick", weight: 3 },
    { pattern: "ill", weight: 3 },
    { pattern: "illness", weight: 3 },
    { pattern: "doctor", weight: 3 },
    { pattern: "medication", weight: 3 },
    { pattern: "medicine", weight: 3 },
    { pattern: "symptoms", weight: 3 },
    { pattern: "diagnosis", weight: 3 },
    { pattern: "diagnosed", weight: 4 },
    { pattern: "flu", weight: 3 },
    { pattern: "cold", weight: 2 },
    { pattern: "cough", weight: 2 },
    { pattern: "clinic", weight: 3 },
    { pattern: "allergy", weight: 3 },
    { pattern: "allergic", weight: 3 },
    { pattern: "treatment", weight: 3 },
    { pattern: "recovery", weight: 3 },
    { pattern: "recovering", weight: 3 },
    { pattern: "checkup", weight: 3 },
    { pattern: "checkup appointment", weight: 4 },
    { pattern: "dentist", weight: 3 },
    { pattern: "pain", weight: 2 },
    { pattern: "ache", weight: 2 },
    { pattern: "nausea", weight: 3 },
    { pattern: "dizzy", weight: 3 },
    { pattern: "appointment", weight: 2 },
  ],
  financial: [
    { pattern: "loan", weight: 4 },
    { pattern: "loans", weight: 4 },
    { pattern: "debt", weight: 4 },
    { pattern: "debts", weight: 4 },
    { pattern: "tuition", weight: 4 },
    { pattern: "mortgage", weight: 4 },
    { pattern: "scholarship", weight: 3 },
    { pattern: "salary", weight: 3 },
    { pattern: "paycheck", weight: 3 },
    { pattern: "budget", weight: 3 },
    { pattern: "savings", weight: 3 },
    { pattern: "money", weight: 3 },
    { pattern: "bills", weight: 3 },
    { pattern: "rent", weight: 3 },
    { pattern: "expensive", weight: 2 },
    { pattern: "afford", weight: 3 },
    { pattern: "affording", weight: 3 },
    { pattern: "expenses", weight: 3 },
    { pattern: "spending", weight: 2 },
    { pattern: "spend", weight: 1 },
    { pattern: "cost", weight: 1 },
    { pattern: "costs", weight: 1 },
    { pattern: "price", weight: 1 },
    { pattern: "fees", weight: 2 },
    { pattern: "allowance", weight: 2 },
    { pattern: "broke", weight: 3 },
    { pattern: "poor", weight: 2 },
    { pattern: "wage", weight: 3 },
    { pattern: "financial", weight: 3 },
    { pattern: "finance", weight: 2 },
    { pattern: "saving up", weight: 3 },
    { pattern: "side hustle", weight: 3 },
  ],
  career: [
    { pattern: "interview", weight: 4 },
    { pattern: "internship", weight: 4 },
    { pattern: "intern", weight: 3 },
    { pattern: "resume", weight: 4 },
    { pattern: "cv", weight: 4 },
    { pattern: "promotion", weight: 4 },
    { pattern: "promoted", weight: 4 },
    { pattern: "fired", weight: 4 },
    { pattern: "laid off", weight: 4 },
    { pattern: "hired", weight: 3 },
    { pattern: "career", weight: 3 },
    { pattern: "boss", weight: 3 },
    { pattern: "manager", weight: 3 },
    { pattern: "supervisor", weight: 3 },
    { pattern: "workplace", weight: 3 },
    { pattern: "colleague", weight: 2 },
    { pattern: "coworker", weight: 2 },
    { pattern: "coworkers", weight: 2 },
    { pattern: "office", weight: 2 },
    { pattern: "shift", weight: 2 },
    { pattern: "overtime", weight: 2 },
    { pattern: "meeting", weight: 2 },
    { pattern: "meetings", weight: 2 },
    { pattern: "work", weight: 2 },
    { pattern: "working", weight: 2 },
    { pattern: "job", weight: 3 },
    { pattern: "jobs", weight: 3 },
    { pattern: "mentor", weight: 3 },
    { pattern: "networking", weight: 3 },
    { pattern: "linkedin", weight: 3 },
    { pattern: "salary", weight: 2 },
  ],
  social: [
    { pattern: "friend", weight: 3 },
    { pattern: "friends", weight: 3 },
    { pattern: "classmates", weight: 2 },
    { pattern: "classmate", weight: 2 },
    { pattern: "party", weight: 3 },
    { pattern: "parties", weight: 3 },
    { pattern: "hangout", weight: 3 },
    { pattern: "hang out", weight: 3 },
    { pattern: "hanging out", weight: 3 },
    { pattern: "social", weight: 2 },
    { pattern: "socializing", weight: 3 },
    { pattern: "socialize", weight: 3 },
    { pattern: "squad", weight: 3 },
    { pattern: "teammates", weight: 2 },
    { pattern: "teammate", weight: 2 },
    { pattern: "roommate", weight: 2 },
    { pattern: "roommates", weight: 2 },
    { pattern: "catch up", weight: 2 },
    { pattern: "gathering", weight: 2 },
    { pattern: "gathered", weight: 2 },
    { pattern: "birthday", weight: 3 },
    { pattern: "invited", weight: 2 },
    { pattern: "celebration", weight: 2 },
    { pattern: "sleepover", weight: 2 },
    { pattern: "get together", weight: 2 },
    { pattern: "chill", weight: 1 },
    { pattern: "fun", weight: 1 },
    { pattern: "together", weight: 1 },
    { pattern: "group", weight: 1 },
  ],
  "self-care": [
    { pattern: "self-care", weight: 5 },
    { pattern: "self care", weight: 5 },
    { pattern: "meditation", weight: 4 },
    { pattern: "meditating", weight: 4 },
    { pattern: "mindfulness", weight: 4 },
    { pattern: "mindful", weight: 3 },
    { pattern: "journal", weight: 2 },
    { pattern: "journaling", weight: 3 },
    { pattern: "yoga", weight: 4 },
    { pattern: "meditate", weight: 4 },
    { pattern: "spa", weight: 4 },
    { pattern: "massage", weight: 4 },
    { pattern: "bubble bath", weight: 4 },
    { pattern: "skincare", weight: 3 },
    { pattern: "recharge", weight: 4 },
    { pattern: "recharging", weight: 4 },
    { pattern: "reset", weight: 2 },
    { pattern: "unwind", weight: 3 },
    { pattern: "unwinding", weight: 3 },
    { pattern: "me time", weight: 5 },
    { pattern: "alone time", weight: 4 },
    { pattern: "rest", weight: 1 },
    { pattern: "resting", weight: 2 },
    { pattern: "relax", weight: 2 },
    { pattern: "relaxing", weight: 2 },
    { pattern: "breathe", weight: 2 },
    { pattern: "breathing", weight: 2 },
    { pattern: "gratitude", weight: 3 },
    { pattern: "boundaries", weight: 3 },
    { pattern: "prayer", weight: 3 },
    { pattern: "praying", weight: 3 },
  ],
  achievements: [
    { pattern: "achievement", weight: 4 },
    { pattern: "achieved", weight: 4 },
    { pattern: "accomplishment", weight: 4 },
    { pattern: "accomplished", weight: 4 },
    { pattern: "accomplish", weight: 3 },
    { pattern: "passed", weight: 4 },
    { pattern: "pass the", weight: 4 },
    { pattern: "won", weight: 3 },
    { pattern: "win", weight: 2 },
    { pattern: "award", weight: 4 },
    { pattern: "awards", weight: 4 },
    { pattern: "medal", weight: 3 },
    { pattern: "trophy", weight: 4 },
    { pattern: "milestone", weight: 4 },
    { pattern: "graduated", weight: 4 },
    { pattern: "graduation", weight: 4 },
    { pattern: "graduate", weight: 3 },
    { pattern: "success", weight: 2 },
    { pattern: "successful", weight: 3 },
    { pattern: "succeeded", weight: 3 },
    { pattern: "succeed", weight: 3 },
    { pattern: "proud", weight: 2 },
    { pattern: "top of the class", weight: 5 },
    { pattern: "dean's list", weight: 5 },
    { pattern: "recognized", weight: 3 },
    { pattern: "met my goal", weight: 4 },
    { pattern: "reached my goal", weight: 4 },
  ],
  sports: [
    { pattern: "basketball", weight: 4 },
    { pattern: "football", weight: 4 },
    { pattern: "soccer", weight: 4 },
    { pattern: "volleyball", weight: 4 },
    { pattern: "baseball", weight: 4 },
    { pattern: "badminton", weight: 4 },
    { pattern: "tennis", weight: 4 },
    { pattern: "swimming", weight: 4 },
    { pattern: "swim", weight: 3 },
    { pattern: "workout", weight: 4 },
    { pattern: "gym", weight: 3 },
    { pattern: "exercise", weight: 3 },
    { pattern: "exercising", weight: 3 },
    { pattern: "running", weight: 3 },
    { pattern: "run", weight: 2 },
    { pattern: "jog", weight: 3 },
    { pattern: "jogging", weight: 3 },
    { pattern: "training", weight: 3 },
    { pattern: "train", weight: 2 },
    { pattern: "tournament", weight: 4 },
    { pattern: "championship", weight: 4 },
    { pattern: "marathon", weight: 4 },
    { pattern: "athlete", weight: 4 },
    { pattern: "coach", weight: 3 },
    { pattern: "match", weight: 3 },
    { pattern: "fitness", weight: 3 },
    { pattern: "cardio", weight: 3 },
    { pattern: "stretch", weight: 2 },
    { pattern: "stretching", weight: 2 },
    { pattern: "bike", weight: 2 },
    { pattern: "cycling", weight: 3 },
    { pattern: "hiking", weight: 3 },
    { pattern: "dance", weight: 2 },
    { pattern: "dancing", weight: 2 },
    { pattern: "game", weight: 1 },
    { pattern: "team", weight: 1 },
    { pattern: "practice", weight: 2 },
    { pattern: "competition", weight: 3 },
    { pattern: "ball", weight: 2 },
  ],
  sleep: [
    { pattern: "insomnia", weight: 5 },
    { pattern: "all-nighter", weight: 5 },
    { pattern: "sleep deprived", weight: 5 },
    { pattern: "sleep schedule", weight: 4 },
    { pattern: "overslept", weight: 4 },
    { pattern: "nightmare", weight: 3 },
    { pattern: "slept", weight: 3 },
    { pattern: "sleeping", weight: 3 },
    { pattern: "sleep", weight: 3 },
    { pattern: "sleepy", weight: 3 },
    { pattern: "drowsy", weight: 3 },
    { pattern: "exhausted", weight: 3 },
    { pattern: "exhaustion", weight: 4 },
    { pattern: "tired", weight: 3 },
    { pattern: "fatigue", weight: 4 },
    { pattern: "awake", weight: 3 },
    { pattern: "woke", weight: 2 },
    { pattern: "waking", weight: 2 },
    { pattern: "wake up", weight: 2 },
    { pattern: "nap", weight: 3 },
    { pattern: "napped", weight: 2 },
    { pattern: "napping", weight: 2 },
    { pattern: "bedtime", weight: 3 },
    { pattern: "bed", weight: 1 },
    { pattern: "caffeine", weight: 2 },
    { pattern: "coffee", weight: 1 },
    { pattern: "energy", weight: 1 },
  ],
  travel: [
    { pattern: "vacation", weight: 4 },
    { pattern: "holiday", weight: 3 },
    { pattern: "trip", weight: 3 },
    { pattern: "trips", weight: 3 },
    { pattern: "travel", weight: 3 },
    { pattern: "traveling", weight: 3 },
    { pattern: "travelling", weight: 3 },
    { pattern: "flight", weight: 3 },
    { pattern: "airport", weight: 4 },
    { pattern: "passport", weight: 4 },
    { pattern: "destination", weight: 4 },
    { pattern: "road trip", weight: 4 },
    { pattern: "backpacking", weight: 4 },
    { pattern: "sightseeing", weight: 4 },
    { pattern: "abroad", weight: 4 },
    { pattern: "overseas", weight: 4 },
    { pattern: "itinerary", weight: 3 },
    { pattern: "luggage", weight: 3 },
    { pattern: "suitcase", weight: 3 },
    { pattern: "hotel", weight: 3 },
    { pattern: "hostel", weight: 3 },
    { pattern: "tourist", weight: 3 },
    { pattern: "tour", weight: 2 },
    { pattern: "explore", weight: 2 },
    { pattern: "exploring", weight: 2 },
    { pattern: "fly", weight: 2 },
    { pattern: "bus", weight: 1 },
    { pattern: "train", weight: 2 },
    { pattern: "commute", weight: 1 },
  ],
  hobbies: [
    { pattern: "hobby", weight: 4 },
    { pattern: "hobbies", weight: 4 },
    { pattern: "paint", weight: 3 },
    { pattern: "painting", weight: 4 },
    { pattern: "draw", weight: 3 },
    { pattern: "drawing", weight: 4 },
    { pattern: "art", weight: 2 },
    { pattern: "guitar", weight: 4 },
    { pattern: "piano", weight: 4 },
    { pattern: "music", weight: 2 },
    { pattern: "singing", weight: 3 },
    { pattern: "photography", weight: 4 },
    { pattern: "cooking", weight: 3 },
    { pattern: "baking", weight: 4 },
    { pattern: "crochet", weight: 4 },
    { pattern: "knitting", weight: 4 },
    { pattern: "sewing", weight: 3 },
    { pattern: "pottery", weight: 4 },
    { pattern: "craft", weight: 3 },
    { pattern: "crafts", weight: 3 },
    { pattern: "gardening", weight: 4 },
    { pattern: "planting", weight: 3 },
    { pattern: "reading", weight: 2 },
    { pattern: "read", weight: 1 },
    { pattern: "book", weight: 1 },
    { pattern: "books", weight: 2 },
    { pattern: "gaming", weight: 3 },
    { pattern: "chess", weight: 4 },
    { pattern: "puzzle", weight: 3 },
    { pattern: "puzzles", weight: 3 },
    { pattern: "writing", weight: 2 },
    { pattern: "blog", weight: 3 },
    { pattern: "podcast", weight: 2 },
    { pattern: "anime", weight: 2 },
    { pattern: "manga", weight: 3 },
    { pattern: "collecting", weight: 3 },
  ],
  "mental-wellness": [
    { pattern: "panic attack", weight: 5 },
    { pattern: "mental health", weight: 4 },
    { pattern: "mental illness", weight: 4 },
    { pattern: "suicidal", weight: 5 },
    { pattern: "self-harm", weight: 5 },
    { pattern: "overthinking", weight: 4 },
    { pattern: "racing thoughts", weight: 4 },
    { pattern: "anxiety", weight: 4 },
    { pattern: "anxious", weight: 4 },
    { pattern: "depression", weight: 4 },
    { pattern: "depressed", weight: 4 },
    { pattern: "panic", weight: 4 },
    { pattern: "panicking", weight: 4 },
    { pattern: "burnout", weight: 4 },
    { pattern: "burnt out", weight: 4 },
    { pattern: "burned out", weight: 4 },
    { pattern: "therapy", weight: 3 },
    { pattern: "therapist", weight: 4 },
    { pattern: "counselor", weight: 4 },
    { pattern: "counseling", weight: 4 },
    { pattern: "coping", weight: 3 },
    { pattern: "coping mechanism", weight: 4 },
    { pattern: "stress", weight: 3 },
    { pattern: "stressed", weight: 3 },
    { pattern: "stressful", weight: 3 },
    { pattern: "overwhelmed", weight: 4 },
    { pattern: "overwhelm", weight: 4 },
    { pattern: "dread", weight: 4 },
    { pattern: "hopeless", weight: 4 },
    { pattern: "helpless", weight: 3 },
    { pattern: "mood swings", weight: 4 },
    { pattern: "triggers", weight: 3 },
    { pattern: "numb", weight: 3 },
    { pattern: "ptsd", weight: 5 },
    { pattern: "worry", weight: 2 },
    { pattern: "worried", weight: 2 },
    { pattern: "fear", weight: 2 },
    { pattern: "afraid", weight: 2 },
    { pattern: "scared", weight: 2 },
  ],
};

const regexCache: Record<string, RegExp> = {};
const weightCache: Record<string, Map<string, number>> = {};

function topicRegex(topic: string): RegExp {
  if (!regexCache[topic]) {
    const patterns = TOPIC_KEYWORDS[topic].map((k) => k.pattern);
    regexCache[topic] = new RegExp(
      `\\b(?:${patterns.join("|")})\\b`,
      "gi",
    );
  }
  return regexCache[topic];
}

function topicWeights(topic: string): Map<string, number> {
  if (!weightCache[topic]) {
    const map = new Map<string, number>();
    for (const k of TOPIC_KEYWORDS[topic]) {
      map.set(k.pattern.toLowerCase(), k.weight);
    }
    weightCache[topic] = map;
  }
  return weightCache[topic];
}

export interface TopicScore {
  topic: string;
  score: number;
  confidence: number; // 0..1 share of total score
}

/**
 * Scores the text against every topic bank and returns matches sorted by
 * score descending, with confidence (score / total) for each.
 */
export function detectTopics(text: string): TopicScore[] {
  const scores: { topic: string; score: number }[] = [];
  let total = 0;

  for (const topic of Object.keys(TOPIC_KEYWORDS)) {
    const regex = topicRegex(topic);
    const weights = topicWeights(topic);
    let score = 0;
    for (const match of text.matchAll(regex)) {
      const word = match[0].toLowerCase();
      score += weights.get(word) ?? 0;
    }
    if (score > 0) {
      scores.push({ topic, score });
      total += score;
    }
  }

  scores.sort((a, b) => b.score - a.score);
  return scores.map((s) => ({
    ...s,
    confidence: total > 0 ? s.score / total : 0,
  }));
}

export function getTopicLabel(topic: string): string {
  return TOPIC_LABELS[topic] ?? topic;
}
